### PR TITLE
Corrected various spellings

### PR DESCRIPTION
**Pull request by hopkins9942**
Hi Adam, I have made the spelling corrections as requested, I hope it's satisfactory!

(Matthew Hopkins)

### CODE REVIEW

**Comment by adamamiller** [comment]
Great! I'm going to close this PR so others can complete the assignment. 

Side note - it looks like this was submitted as an entirely different pull request. It's possible to send updates on the initial changes that you made (which may be helpful for future software development projects that you work on).

**Comment by hopkins9942** [comment]
Hi Adam, 

Apologies, I am unfamiliar with pull requests. What do you mean by "an entirely different pull request"? I am aware of the possibility of sending updates on the initial changes, however I think I did all of the corrections in one commit and one pull request - is this correct?

**Comment by adamamiller** [comment]
I made a mistake! I thought you had previously made a submission and that I asked you to update that submission (none of which actually happened). Everything was one commit and PR so you can ignore what I said.

**Comment by hopkins9942** [comment]
Ahh brill, thanks!

**Pull request closed without merging**
